spring:
  rabbitmq:
    addresses: 192.168.199.113:5672,192.168.199.114:5672
    username: demo
    password: 1990912
    virtual-host: demo
    connection-timeout: 60000
  zipkin:
    base-url: http://localhost:9411/
#    sender:
#      type: rabbit
#    discovery-client-enabled: true
#    locator:
#      discovery:
#        enabled: true
  sleuth:
    sampler:
      probability: 1.0
server:
  servlet:
    context-path: /demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/