spring:
  rabbitmq:
    addresses: 192.168.199.113:5672,192.168.199.114:5672
    username: demo
    password: 1990912
    virtual-host: demo
    connection-timeout: 60000
  cloud:
    stream:
      bindings:
        order_to_purchase_01:
          group: demo_stream_order
          destination: demo.order_to_purchase_01
          content-type: application/json
        order_to_mall_01:
          group: demo_stream_order
          destination: demo.order_to_mall_01
          content-type: application/json
          producer:
            partition-key-expression: payload.from
            partition-count: 2
        order_to_purchase_redirect_mall_01:
          group: demo_stream_order
          destination: demo.order_to_purchase_redirect_mall_01
          content-type: application/json
server:
  port: 8871
  servlet:
    context-path: /demo